### ISSUE TITLE
Kodi XVDR development state

### ISSUE THREAD

**Issue by dreasb** [pipelka/vdr-plugin-xvdr#131]
Can you please provide some more details about your add-on roadmap KODI-XVDR? 
Do you plan to cancel your activities for XVDR add-on KODI? Hopefully not, I like this add-on!

My experience: It seems that the current stable KODI-15.2 version has updated the EPG database schema and your add-on does not support the new database structure. However it is possible to bring it runnable without EPG data. KODI-16.0b3: add-on will be automatically deactivated after activation. KODI-17: Incompatible add-on version 4.x.x is incompatible with 1.9.x.

Thanks for a short replay,
Best regards from Munich, Germany

**Comment by pipelka** [comment]
Hi,

To be honest, I'm not using xbmc anymore. I'm still using the xvdr
infrastructure to distribute and watch tv in my home but without xbmc as
frontend.

I really never was happy with the xbmc philosophy and now it's possible to
do all i wanted to do without it.

Anyone who wants to adopt the xbmc frontend may do it and continue
development. I will concentrate on different things being fully under my
control.

Regards,
Alex

**Comment by dreasb** [comment]
Hi Alex,

thanks for your reply. 

Can you post it on your add-on related info page or put it into your readme file? I believe this information is interesting for other peoples, too.  

Have a nice Christmas time!
